#!/usr/bin/env bash
# shellcheck disable=SC2016
# installing and config load balancer
apt-get -y install haproxy

echo "ENABLED=1" >> /etc/default/haproxy

server_config=\ "
frontend load_balancer
    bind *:80
    mode http
    default_backend webserver
backend webserver
    balance roundrobin
    server 2550-web-01 54.167.76.237 check
    server 2550-web-02 3.85.184.176 check
"
echo "$server_config" >> /etc/haproxy/haproxy.cfg
service haproxy restart
