#!/usr/bin/env bash
# config nginx server to listen to port 80 short way
cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default 
service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
